# Namespaces for different application
namespaces:
  - "jenkins"

images:
  jenkins:
    image: "jenkins/jenkins"
    tag: "jdk17"

containerPorts:
  jenkins: 8080


persistentVolumeandClaims:
  jenkins:
    pvcName: "jenkins-home-pvc"
    pvName: "jenkins-home-pv"
    pvHostPath: "/var/k8s/chat-app"
